#!/usr/bin/env python3
import argparse
import random
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


PROGRAMS = [
    "navparse",
    "ubxtool",
    "navnexus",
    "navcat",
    "navrecv",
    "navdump",
    "testrunner",
    "navdisplay",
    "tlecatch",
    "reporter",
    "sp3feed",
    "galmonmon",
    "rinreport",
    "rinjoin",
    "rtcmtool",
    "gndate",
    "septool",
    "navmerge",
]


def get_valgrind_prefix(error_exitcode: int) -> list[str]:
    return [
        "valgrind",
        "--quiet",
        "--leak-check=full",
        "--show-leak-kinds=all",
        "--errors-for-leak-kinds=definite,possible,indirect",
        f"--error-exitcode={error_exitcode}",
    ]


def build_random_blob(seed: int, size: int) -> bytes:
    rng = random.Random(seed)
    return bytes(rng.getrandbits(8) for _ in range(size))


def build_malformed_blob() -> bytes:
    # Mixed binary garbage with truncated framing-like markers.
    return b"\xb5\x62\x01\x07\xff\xff\x00\x00garbage\xff\xfe\n\x80\x81"


def build_valid_ubx_nav_pvt_frame() -> bytes:
    payload = bytearray(92)
    payload[4:6] = (2026).to_bytes(2, "little")
    payload[6] = 4
    payload[7] = 16
    payload[8] = 12
    payload[9] = 34
    payload[10] = 56
    payload[11] = 0x07
    payload[20] = 3
    body = bytes([0x01, 0x07]) + len(payload).to_bytes(2, "little") + bytes(payload)
    ck_a = 0
    ck_b = 0
    for b in body:
        ck_a = (ck_a + b) & 0xFF
        ck_b = (ck_b + ck_a) & 0xFF
    return b"\xb5\x62" + body + bytes([ck_a, ck_b])


def build_minimal_rinex() -> bytes:
    return (
        b"     3.04           OBSERVATION DATA    M (MIXED)           RINEX VERSION / TYPE\n"
        b"GENERATED BY APPS HARNESS                              PGM / RUN BY / DATE\n"
        b"                                                            END OF HEADER\n"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run crash-safety checks over all compiled applications.")
    parser.add_argument("--timeout-seconds", type=float, default=5.0, help="Per-app timeout in seconds (default: 5).")
    parser.add_argument("--version-flag", default="--version", help="Flag passed to each binary (default: --version).")
    parser.add_argument("--random-bytes", type=int, default=512, help="Random-input payload size (default: 512).")
    parser.add_argument("--seed", type=int, default=20260416, help="Seed for deterministic random input (default: 20260416).")
    parser.add_argument("--valgrind", action="store_true", help="Run each app invocation under valgrind memcheck.")
    parser.add_argument(
        "--valgrind-error-exitcode",
        type=int,
        default=99,
        help="Exit code valgrind uses when memory errors are detected (default: 99).",
    )
    parser.add_argument(
        "--log-dir",
        default="apps-smoke-logs",
        help="Directory where per-case stdout/stderr logs are written (default: apps-smoke-logs).",
    )
    parser.add_argument(
        "--no-emit-output",
        action="store_true",
        help="Do not print captured stdout/stderr to console; logs are still written.",
    )
    return parser.parse_args()


def write_temp_blob(data: bytes, suffix: str) -> str:
    with tempfile.NamedTemporaryFile(prefix="apps-smoke-", suffix=suffix, delete=False) as fp:
        fp.write(data)
        return fp.name


def build_program_cases(
    program: str, version_flag: str, random_blob: bytes, malformed_blob: bytes, valid_blob: bytes
) -> list[tuple[str, list[str], bytes | None, bool]]:
    # Per-app explicit case table: (name, args, stdin, needs_temp_file)
    # When needs_temp_file=True, "{TMP}" in args is replaced with a generated temp file path.
    app_cases: dict[str, list[tuple[str, list[str], bytes | None, bool]]] = {
        "navparse": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "ubxtool": [
            ("valid", [version_flag], None, False),
            ("random", ["--port", "{TMP}", "--station", "1", "--stdout"], random_blob, True),
            ("malformed", ["--port", "{TMP}", "--station", "1", "--stdout"], malformed_blob, True),
        ],
        "navnexus": [("valid", [version_flag], None, False), ("random", ["--", random_blob.hex()[:32]], None, False), ("malformed", ["---bad-flag"], None, False)],
        "navcat": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "navrecv": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "navdump": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "testrunner": [("valid", [], None, False), ("random", ["--", random_blob.hex()[:32]], None, False), ("malformed", ["---bad-flag"], None, False)],
        "navdisplay": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "tlecatch": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "reporter": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "sp3feed": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "galmonmon": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
        "rinreport": [
            ("valid", [version_flag], None, False),
            ("random", ["{TMP}"], random_blob, True),
            ("malformed", ["{TMP}"], malformed_blob, True),
        ],
        "rinjoin": [
            ("valid", [version_flag], None, False),
            ("random", ["{TMP}"], random_blob, True),
            ("malformed", ["{TMP}"], malformed_blob, True),
        ],
        "rtcmtool": [("valid", [version_flag], None, False), ("random", ["--station", "1"], random_blob, False), ("malformed", ["--station", "1"], malformed_blob, False)],
        "gndate": [("valid", [version_flag], None, False), ("random", ["--", random_blob.hex()[:32]], None, False), ("malformed", ["---bad-flag"], None, False)],
        "septool": [("valid", [version_flag], None, False), ("random", ["--station", "1"], random_blob, False), ("malformed", ["--station", "1"], malformed_blob, False)],
        "navmerge": [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)],
    }
    if program not in app_cases:
        return [("valid", [version_flag], None, False), ("random", [], random_blob, False), ("malformed", [], malformed_blob, False)]

    return app_cases[program]


def run_case(
    program: str,
    binary: Path,
    case_name: str,
    app_args: list[str],
    stdin_data: bytes | None,
    timeout_seconds: float,
    use_valgrind: bool,
    valgrind_error_exitcode: int,
) -> tuple[bool, str, bytes, bytes]:
    cmd = [str(binary)] + app_args
    if use_valgrind:
        cmd = get_valgrind_prefix(valgrind_error_exitcode) + cmd
    try:
        proc = subprocess.run(
            cmd,
            input=stdin_data,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout_seconds,
        )
    except subprocess.TimeoutExpired:
        return False, f"{program}:{case_name}: timeout (> {timeout_seconds}s)", b"", b""

    if proc.returncode < 0:
        return False, f"{program}:{case_name}: crashed with signal {-proc.returncode}", proc.stdout, proc.stderr
    if use_valgrind and proc.returncode == valgrind_error_exitcode:
        return (
            False,
            f"{program}:{case_name}: valgrind reported memory errors (exit={proc.returncode})",
            proc.stdout,
            proc.stderr,
        )
    return True, f"{program}:{case_name}: exit={proc.returncode}", proc.stdout, proc.stderr


def write_case_logs(log_dir: Path, program: str, case_name: str, stdout_data: bytes, stderr_data: bytes) -> tuple[Path, Path]:
    log_dir.mkdir(parents=True, exist_ok=True)
    base = f"{program}.{case_name}"
    stdout_path = log_dir / f"{base}.stdout.log"
    stderr_path = log_dir / f"{base}.stderr.log"
    stdout_path.write_bytes(stdout_data)
    stderr_path.write_bytes(stderr_data)
    return stdout_path, stderr_path


def emit_case_output(program: str, case_name: str, stdout_data: bytes, stderr_data: bytes) -> None:
    if stdout_data:
        print(f"--- {program}:{case_name}: stdout ---")
        print(stdout_data.decode("utf-8", errors="replace").rstrip())
    if stderr_data:
        print(f"--- {program}:{case_name}: stderr ---", file=sys.stderr)
        print(stderr_data.decode("utf-8", errors="replace").rstrip(), file=sys.stderr)


def main() -> int:
    args = parse_args()
    if args.random_bytes < 1:
        print("error: --random-bytes must be >= 1", file=sys.stderr)
        return 2
    if args.valgrind and not shutil.which("valgrind"):
        print("error: --valgrind requested, but valgrind is not installed", file=sys.stderr)
        return 2
    root = Path(__file__).resolve().parent.parent
    log_dir = root / args.log_dir
    malformed_blob = build_malformed_blob()
    valid_ubx = build_valid_ubx_nav_pvt_frame()
    valid_rinex = build_minimal_rinex()

    failed = False
    for program in PROGRAMS:
        binary = root / program
        if not binary.exists():
            print(f"{program}: missing binary (build first)")
            failed = True
            continue

        random_blob = build_random_blob(args.seed + len(program), args.random_bytes)
        valid_blob = valid_ubx if program in {"ubxtool", "navparse", "navdump", "rtcmtool", "septool"} else valid_rinex
        cases = build_program_cases(program, args.version_flag, random_blob, malformed_blob, valid_blob)
        for case_name, app_args, stdin_data, needs_temp_file in cases:
            temp_path: str | None = None
            effective_args = list(app_args)
            effective_stdin = stdin_data
            if needs_temp_file:
                blob = effective_stdin if effective_stdin is not None else valid_blob
                suffix = ".rnx" if program in {"rinreport", "rinjoin"} else ".bin"
                temp_path = write_temp_blob(blob, suffix)
                effective_args = [arg.replace("{TMP}", temp_path) for arg in effective_args]
                effective_stdin = None
            try:
                ok, message, stdout_data, stderr_data = run_case(
                    program,
                    binary,
                    case_name,
                    effective_args,
                    effective_stdin,
                    args.timeout_seconds,
                    args.valgrind,
                    args.valgrind_error_exitcode,
                )
            finally:
                if temp_path is not None:
                    Path(temp_path).unlink(missing_ok=True)
            print(message)
            stdout_path, stderr_path = write_case_logs(log_dir, program, case_name, stdout_data, stderr_data)
            print(f"{program}:{case_name}: logs -> {stdout_path} | {stderr_path}")
            if not args.no_emit_output:
                emit_case_output(program, case_name, stdout_data, stderr_data)
            if not ok:
                failed = True

    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
