name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: "recursive"
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install protobuf-compiler libcpp-httplib-dev libcurl4-openssl-dev libssl-dev libprotobuf-dev libncurses5-dev libeigen3-dev libzstd-dev libfec-dev libfmt-dev
    - name: make
      run: make
    - name: make check
      run: make check
